export { HomePage } from './App/Home';
export { ContactsPage } from './App/Contacts';
export { MessagesPage } from './App/Messages';
export { TutorialPage } from './App/Tutorial';
export { HomePage as DocsHomePage } from './Docs/Home';
export { OverviewPage } from './Docs/Overview';
export { UsagePage } from './Docs/Usage';
export { BuildPage } from './Docs/Build';
export { ContributePage } from './Docs/Contribute';
export { PrivacyPage } from './Docs/Privacy';
